# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_xss}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["joloudov"]
  s.date = %q{2010-07-14}
  s.description = %q{This plugin replaces the default ERB template handlers with erubis, and switches the behaviour to escape by default rather than requiring you to escape. This is consistent with the behaviour in Rails 3.0.}
  s.email = %q{joloudov@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/rails_xss.rb",
     "lib/rails_xss/action_view.rb",
     "lib/rails_xss/erubis.rb",
     "lib/rails_xss/string_ext.rb",
     "lib/tasks/rails_xss_tasks.rake"
  ]
  s.homepage = %q{http://github.com/joloudov/rails_xss}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A plugin for rails 2.3 apps which switches the default to escape by default}
  s.test_files = [
    "test/deprecated_output_safety_test.rb",
     "test/output_safety_test.rb",
     "test/form_tag_helper_test.rb",
     "test/form_helper_test.rb",
     "test/test_helper.rb",
     "test/erb_util_test.rb",
     "test/date_helper_test.rb",
     "test/active_record_helper_test.rb",
     "test/caching_test.rb",
     "test/text_helper_test.rb",
     "test/asset_tag_helper_test.rb",
     "test/rails_xss_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<erubis>, [">= 2.6.5"])
    else
      s.add_dependency(%q<erubis>, [">= 2.6.5"])
    end
  else
    s.add_dependency(%q<erubis>, [">= 2.6.5"])
  end
end

